// Alla texter i quizet och admin-vyn, per språk. Språket väljs med LANG i config (standard: sv).
(function () {
  const sv = {
    locale: "sv-SE",
    // Quizet
    namePlaceholder: "Förnamn och efternamnets initial",
    join: "Gå med",
    intro: (n, s) => n + " frågor, " + s + " sekunder per fråga. Quizet startar när alla är med, och resultatet visas i topplistan när du är klar.",
    nameLabel: "Ditt namn (visas i topplistan)",
    youreIn: (name) => "Du är med, " + name + "!",
    waitingForQuiz: "Väntar på att quizet ska starta…",
    keepOpen: "Håll sidan öppen. Första frågan visas automatiskt när quizet startar.",
    inTheQuiz: "Med i quizet",
    joinedCount: (n) => n + (n === 1 ? " ansluten" : " anslutna"),
    lostConnection: "Tappade kontakten, försöker igen…",
    questionOf: (i, n) => "Fråga " + i + " av " + n,
    timeLeft: "Tid kvar",
    true: "Sant",
    false: "Falskt",
    answerIn: (unit) => "Ditt svar i " + unit,
    answer: "Svara",
    loadingBoard: "Hämtar topplistan…",
    wellDone: (name) => "Bra jobbat, " + name + "!",
    yourPoints: "Dina poäng",
    ofPossible: (n) => "av " + n + " möjliga",
    leaderboard: "Topplista",
    sendingLast: "Skickar dina sista svar…",
    playing: " spelar…",
    yourPlace: (p, n) => "Du ligger på plats " + p + " av " + n + ". Listan uppdateras automatiskt.",
    boardError: "Kunde inte hämta topplistan, försöker igen…",
    // Admin
    email: "E-post",
    password: "Lösenord",
    wrongLogin: "Fel e-post eller lösenord.",
    logIn: "Logga in",
    countUnit: (n) => n + " st",
    barTooltip: (label, n, pct, correct) => label + ": " + n + " svar (" + pct + " %)" + (correct ? ", rätt svar" : ""),
    answersMeta: (n, pct) => n + " svar" + (pct == null ? "" : " · " + pct + " % rätt"),
    correctAnswer: "Rätt svar: ",
    median: "Median: ",
    range: "Lägst–högst: ",
    correctNames: "Rätt: ",
    timedOutNames: "Hann inte svara: ",
    nameCol: "Namn",
    questionAbbr: "F",
    pointsCol: "Poäng",
    allAnswers: "Alla svar",
    matrixLegend: "✓ rätt · ½ nära (skattning) · ✗ fel · – hann inte svara · · inte kommit dit än. Håll muspekaren över en ruta för att se svaret.",
    resetBoard: "Nollställ topplistan",
    logOut: "Logga ut",
    noPermission: "Du saknar behörighet, logga in igen.",
    actionFailed: "Det gick inte, försök igen.",
    resetConfirm: (session) =>
      "Nollställa topplistan för session ”" + session + "”?\n\nAlla svar och alla anslutna tas bort, och quizet går tillbaka till väntrummet. " +
      "Den som har spelat klart hamnar i väntrummet igen. Den som är mitt i en fråga behöver ladda om sidan.",
    waitingForStart: "väntar på start",
    joinedTile: (n) => (n === 1 ? "ansluten" : "anslutna"),
    waitingForPlayers: "Väntar på deltagare",
    goTo: (url) => ["Gå till ", url, " och skriv ditt namn"],
    nobodyYet: "Ingen har anslutit än…",
    pleaseWait: "Vänta…",
    startQuiz: (n) => "Starta quizet" + (n ? " för " + n + " deltagare" : ""),
    startedInfo: (time, secs) => "startade " + time + " · uppdateras var " + secs + ":e sekund",
    participants: "deltagare",
    finished: "klara",
    avgOf: (n) => "snittpoäng av " + n,
    noAnswers: "Inga svar än…",
    notAdmin: "Kontot har inte admin-behörighet, eller så är facit inte inlagt i databasen.",
    loginAgain: "Du behöver logga in igen.",
    loading: "Laddar…",
  };

  const en = {
    locale: "en-GB",
    // Quiz
    namePlaceholder: "First name and last initial",
    join: "Join",
    intro: (n, s) => n + " questions, " + s + " seconds per question. The quiz starts when everyone is in, and your result appears on the leaderboard when you finish.",
    nameLabel: "Your name (shown on the leaderboard)",
    youreIn: (name) => "You're in, " + name + "!",
    waitingForQuiz: "Waiting for the quiz to start…",
    keepOpen: "Keep this page open. The first question appears automatically when the quiz starts.",
    inTheQuiz: "In the quiz",
    joinedCount: (n) => n + " joined",
    lostConnection: "Lost connection, retrying…",
    questionOf: (i, n) => "Question " + i + " of " + n,
    timeLeft: "Time left",
    true: "True",
    false: "False",
    answerIn: (unit) => "Your answer in " + unit,
    answer: "Answer",
    loadingBoard: "Loading the leaderboard…",
    wellDone: (name) => "Well done, " + name + "!",
    yourPoints: "Your points",
    ofPossible: (n) => "out of " + n,
    leaderboard: "Leaderboard",
    sendingLast: "Sending your last answers…",
    playing: " playing…",
    yourPlace: (p, n) => "You are in place " + p + " of " + n + ". The list updates automatically.",
    boardError: "Could not load the leaderboard, retrying…",
    // Admin
    email: "Email",
    password: "Password",
    wrongLogin: "Wrong email or password.",
    logIn: "Log in",
    countUnit: (n) => String(n),
    barTooltip: (label, n, pct, correct) => label + ": " + n + (n === 1 ? " answer" : " answers") + " (" + pct + "%)" + (correct ? ", correct answer" : ""),
    answersMeta: (n, pct) => n + (n === 1 ? " answer" : " answers") + (pct == null ? "" : " · " + pct + "% correct"),
    correctAnswer: "Correct answer: ",
    median: "Median: ",
    range: "Lowest–highest: ",
    correctNames: "Correct: ",
    timedOutNames: "Ran out of time: ",
    nameCol: "Name",
    questionAbbr: "Q",
    pointsCol: "Points",
    allAnswers: "All answers",
    matrixLegend: "✓ correct · ½ close (estimate) · ✗ wrong · – ran out of time · · not there yet. Hover over a cell to see the answer.",
    resetBoard: "Reset leaderboard",
    logOut: "Log out",
    noPermission: "You don't have permission, please log in again.",
    actionFailed: "That didn't work, please try again.",
    resetConfirm: (session) =>
      "Reset the leaderboard for session “" + session + "”?\n\nAll answers and everyone who joined are removed, and the quiz goes back to the waiting room. " +
      "Players who have finished return to the waiting room. Anyone in the middle of a question needs to reload the page.",
    waitingForStart: "waiting to start",
    joinedTile: () => "joined",
    waitingForPlayers: "Waiting for players",
    goTo: (url) => ["Go to ", url, " and enter your name"],
    nobodyYet: "Nobody has joined yet…",
    pleaseWait: "Please wait…",
    startQuiz: (n) => "Start the quiz" + (n ? " for " + n + (n === 1 ? " player" : " players") : ""),
    startedInfo: (time, secs) => "started " + time + " · updates every " + secs + " seconds",
    participants: "players",
    finished: "finished",
    avgOf: (n) => "average score out of " + n,
    noAnswers: "No answers yet…",
    notAdmin: "This account has no admin access, or the answer key has not been added to the database.",
    loginAgain: "Please log in again.",
    loading: "Loading…",
  };

  const lang = (window.QUIZ_CONFIG && window.QUIZ_CONFIG.LANG) || "sv";
  window.QUIZ_TEXT = lang === "en" ? en : sv;
})();
